# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_vision_loss_functions.ipynb.

# %% auto #0
__all__ = ['CustomLoss', 'TverskyFocalLoss', 'DynUNetDSAdapter']

# %% ../nbs/04_vision_loss_functions.ipynb #e8eee6b3-75c3-4468-8645-8f6a42a76bfe
import torch
from .vision_core import *
from .vision_data import pred_to_binary_mask, batch_pred_to_multiclass_mask
from monai.losses import TverskyLoss, FocalLoss
from torch.nn.modules.loss import _Loss

# %% ../nbs/04_vision_loss_functions.ipynb #e0c0c220-aaeb-46c6-8d18-f72cd9da0555
class CustomLoss:
    """A custom loss wrapper class for loss functions to allow them to work with
    the 'show_results' method in fastai. 
    """

    def __init__(self, loss_func):
        """Constructs CustomLoss object."""
        
        self.loss_func = loss_func

    def __call__(self, pred, targ):
        """Computes the loss for given predictions and targets."""
        
        if isinstance(pred, MedBase):
            pred, targ = torch.Tensor(pred.cpu()), torch.Tensor(targ.cpu().float())

        targ = targ.float()
        return self.loss_func(pred, targ)

    def activation(self, x):
        return x
    
    def decodes(self, x) -> torch.Tensor:
        """Converts model output to target format.
        
        Args:
            x: Activations for each class with dimensions [B, C, W, H, D].

        Returns:
            The predicted mask.
        """
        
        n_classes = x.shape[1]
        if n_classes == 1: 
            x = pred_to_binary_mask(x)
        else: 
            x,_ = batch_pred_to_multiclass_mask(x)

        return x

# %% ../nbs/04_vision_loss_functions.ipynb #5052c7bc-3d9a-4e34-8b64-bceaf2fdc7b6
class TverskyFocalLoss(_Loss):
    """Focal Tversky loss: ``(1 - TI)**gamma`` (TI = Tversky index; see ``monai.losses.TverskyLoss``).
    ``gamma=1`` reduces to the plain Tversky loss.
    """

    def __init__(
        self,
        include_background: bool = True,
        to_onehot_y: bool = False,
        sigmoid: bool = False,
        softmax: bool = False,
        gamma: float = 2,
        alpha: float = 0.5, 
        beta: float = 0.99):
        """
        Args:
            include_background: if to calculate loss for the background class.
            to_onehot_y: whether to convert `y` into one-hot format.
            sigmoid: if True, apply a sigmoid function to the prediction.
            softmax: if True, apply a softmax function to the prediction.
            gamma: focal exponent in ``(1 - TI)**gamma``.
            alpha: the weight of false positive in Tversky loss calculation.
            beta: the weight of false negative in Tversky loss calculation.
        """
            
        super().__init__()
        self.tversky = TverskyLoss(
            to_onehot_y=to_onehot_y, 
            include_background=include_background, 
            sigmoid=sigmoid, 
            softmax=softmax, 
            alpha=alpha, 
            beta=beta
        )
        self.gamma = gamma

    def forward(self, input: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """
        Args:
            input: the shape should be [B, C, W, H, D]. The input should be the original logits.
            target: the shape should be[B, C, W, H, D].

        Raises:
            ValueError: When number of dimensions for input and target are different.
        """
        if len(input.shape) != len(target.shape):
            raise ValueError("The number of dimensions for input and target should be the same.")

        # (1 - TI)**gamma; MONAI's TverskyLoss already returns tversky_loss = 1 - TI
        tversky_loss = self.tversky(input, target)
        total_loss: torch.Tensor = tversky_loss ** self.gamma

        return total_loss

# %% ../nbs/04_vision_loss_functions.ipynb #acf08940
class DynUNetDSAdapter(torch.nn.Module):
    """Wrap a MONAI ``DynUNet`` with deep supervision so its output matches what
    ``monai.losses.DeepSupervisionLoss`` (used via ``CustomLoss``) expects.

    A ``DynUNet(deep_supervision=True)`` returns a *stacked* ``[B, N, C, ...]`` tensor in
    training (a TorchScript workaround), but ``DeepSupervisionLoss`` only unbinds a *list* of
    tensors -- a stacked tensor would fall through to the base loss and be scored incorrectly.
    This adapter unbinds the stack into that list in training, and passes the plain prediction
    through in eval mode (MONAI's ``DynUNet`` docstring prescribes exactly this ``torch.unbind``).

    Note: wrapping registers the network as ``self.model``, so it adds a ``model.`` prefix to
    state-dict keys -- relevant when loading raw ``.pth`` checkpoints of a wrapped model.
    """

    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x):
        out = self.model(x)
        # Unbind only in training, and only when the wrapped net actually stacks its
        # deep-supervision heads. Gating on `deep_supervision` (not output rank) keeps this
        # correct for 2D and 3D alike, and fails loudly if wrapped around a non-DynUNet in training.
        if self.model.training and self.model.deep_supervision:
            return list(torch.unbind(out, dim=1))
        return out
