name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
      - name: Test vestibular schwannoma workflows and deployment
        env:
          PYTHONPATH: research:research/vestibular_schwannoma
        run: |
          python -m pip install pytest
          python -m pytest -q research/vestibular_schwannoma/tests
